# Generated by Django 3.2 on 2024-05-26 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentoCarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.FloatField(null=True)),
                ('archivo', models.FileField(default=None, upload_to='')),
                ('estado', models.IntegerField(default=1)),
                ('tipo', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
